export const questionData: any = [
  {
    questionContent: "1.您对xxx人员服务满意吗？",
    id: 1,
    type: "单选",
    answer: [
      { content: "很满意", count: 1, ratio: "4.17" },
      { content: "满意", count: 3, ratio: "12.50" },
      { content: "一般", count: 6, ratio: "25.00" },
      { content: "不满意", count: 11, ratio: "45.83" },
      { content: "很不满意", count: 2, ratio: "8.33" },
      { content: "未接触", count: 1, ratio: "4.17" },
    ],
    typeShow: true,
    assessCount: 24,
  },
  {
    questionContent: "2.您认为xxx清晰吗？",
    id: 2,
    type: "单选",
    answer: [
      { content: "很满意", count: 1, ratio: "4.17" },
      { content: "满意", count: 4, ratio: "16.67" },
      { content: "一般", count: 10, ratio: "41.67" },
      { content: "不满意", count: 7, ratio: "29.17" },
      { content: "很不满意", count: 1, ratio: "4.17" },
      { content: "没注意", count: 1, ratio: "4.17" },
    ],
    typeShow: true,
    assessCount: 24,
  },
  {
    questionContent: "3.您认为xxx准确吗？",
    id: 3,
    type: "单选",
    answer: [
      { content: "很满意", count: 0, ratio: "0.00" },
      { content: "满意", count: 3, ratio: "12.50" },
      { content: "一般", count: 16, ratio: "66.67" },
      { content: "不满意", count: 3, ratio: "12.50" },
      { content: "没看到", count: 2, ratio: "8.33" },
    ],
    typeShow: true,
    assessCount: 24,
  },
  {
    questionContent: "4.您对xxx满意吗？",
    id: 4,
    type: "单选",
    answer: [
      { content: "很满意", count: 0, ratio: "0.00" },
      { content: "满意", count: 7, ratio: "29.17" },
      { content: "一般", count: 7, ratio: "29.17" },
      { content: "不满意", count: 5, ratio: "20.83" },
      { content: "很不满意", count: 3, ratio: "12.50" },
      { content: "未检查", count: 2, ratio: "8.33" },
    ],
    typeShow: true,
    assessCount: 24,
  },
  {
    questionContent: "5.您对xxx报告满意吗？",
    id: 5,
    type: "单选",
    answer: [
      { content: "很满意", count: 0, ratio: "0.00" },
      { content: "满意", count: 7, ratio: "29.17" },
      { content: "一般", count: 8, ratio: "33.33" },
      { content: "不满意", count: 7, ratio: "29.17" },
      { content: "很不满意", count: 1, ratio: "4.17" },
      { content: "未检查", count: 1, ratio: "4.17" },
    ],
    typeShow: true,
    assessCount: 24,
  },
  {
    questionContent: "6.您对xxx等候时间满意吗？",
    id: 6,
    type: "单选",
    answer: [
      { content: "很满意", count: 1, ratio: "4.17" },
      { content: "满意", count: 9, ratio: "37.50" },
      { content: "一般", count: 4, ratio: "16.67" },
      { content: "不满意", count: 6, ratio: "25.00" },
      { content: "很不满意", count: 3, ratio: "12.50" },
      { content: "未检查", count: 1, ratio: "4.17" },
    ],
    typeShow: true,
    assessCount: 24,
  },
  {
    questionContent: "7.您对下列那些工作人员感到不满意？",
    id: 7,
    type: "多选",
    answer: [
      { content: "门卫人员", count: 2, ratio: "1.80" },
      { content: "食堂人员", count: 5, ratio: "4.50" },
      { content: "环卫人员", count: 12, ratio: "10.81" },
      { content: "导诊人员", count: 15, ratio: "13.51" },
      { content: "检验人员", count: 14, ratio: "12.61" },
      { content: "前台人员", count: 14, ratio: "12.61" },
      { content: "维修人员", count: 8, ratio: "7.21" },
      { content: "收费人员", count: 11, ratio: "9.91" },
      { content: "保洁人员", count: 10, ratio: "9.01" },
      { content: "保安人员", count: 9, ratio: "8.11" },
      { content: "投诉接待人员", count: 4, ratio: "3.60" },
      { content: "都满意", count: 7, ratio: "6.31" },
    ],
    typeShow: true,
    assessCount: 111,
  },
  {
    questionContent: "8.请输入原因",
    id: 8,
    type: "填空",
    answer: [],
    fillAnswer: [
      { id: 1, content: "234xxx", time: "2022-05-27 16:03:05" },
      { id: 2, content: "333dffd", time: "2022-05-27 16:02:14" },
      { id: 3, content: "1213d21", time: "2022-05-27 16:01:35" },
      { id: 4, content: "1212fg1", time: "2022-05-27 15:56:17" },
      { id: 5, content: "122q23121", time: "2022-05-27 15:52:15" },
      { id: 6, content: "1xc23", time: "2022-05-27 15:43:15" },
      { id: 7, content: "11", time: "2022-05-27 15:41:17" },
      { id: 8, content: "1212", time: "2022-05-27 15:40:22" },
    ],
    typeShow: false,
    assessCount: 0,
  },
];
